name: run-tests

on:
    push:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.1, 8.0, 7.4, 7.3]
                laravel: [9.*, 8.*, 7.*]
                dependency-version: [prefer-stable]
                include:
                    - laravel: 9.*
                      testbench: 7.*
                    - laravel: 8.*
                      testbench: 6.*
                    - laravel: 7.*
                      testbench: 5.*
                exclude:
                    - php: 8.1
                      laravel: 7.*
                    - php: 7.3
                      laravel: 9.*
                    - php: 7.4
                      laravel: 9.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
